### PR TITLE
Require Doctrine Migrations 3.x, support PHP 8.2/8.3 and TYPO3 v12

### PR DESCRIPTION
**Pull request by andreaswolf**

### CODE REVIEW

**Comment by baschny** [comment]
Don't know if you wanted to continue working on it, but it turned up to be more work than expected at first, but it worked. Here is the completion:

https://github.com/andreaswolf/typo3-ext-migrations/pull/23

Please take a look, maybe we could finish that off and make a release compatible with TYPO3 v11 and v12 soon.

**Comment by andreaswolf** [comment]
There seems to be a regression in doctrine/migrations 3.7.1 or 3.7.0, since the pipelines worked with 3.6.0 (in PR #23).

**Comment by andreaswolf** [comment]
> There seems to be a regression in doctrine/migrations 3.7.1 or 3.7.0, since the pipelines worked with 3.6.0 (in PR #23).

This is due to https://github.com/doctrine/migrations/pull/1363/files, but it seems to be a TYPO3 Core bug, where `DateTimeImmutable` instances are not correctly processed in `Connection::ensureDatabaseValueTypes()`.

**Comment by baschny** [comment]
@andreaswolf great that you took over. I will have no time to follow-up on that in the next days, so either you continue to tackle that or I can also take a look at it in a near future.

**Comment by andreaswolf** [comment]
> > There seems to be a regression in doctrine/migrations 3.7.1 or 3.7.0, since the pipelines worked with 3.6.0 (in PR #23).
> 
> This is due to https://github.com/doctrine/migrations/pull/1363/files, but it seems to be a TYPO3 Core bug, where `DateTimeImmutable` instances are not correctly processed in `Connection::ensureDatabaseValueTypes()`.

I opened a bug on TYPO3 Forge: https://forge.typo3.org/issues/102479 and pushed a patch already.

**Comment by andreaswolf** [comment]
> I opened a bug on TYPO3 Forge: https://forge.typo3.org/issues/102479 and pushed a patch already.

The patch has been released in TYPO3 12.4.9, which should now become the minimum supported 12.x version of this extension.

**Comment by baschny** [comment]
Horray! 👍

**Pull request merged**
