### PR TITLE
Prepare suitability for v11 of TYPO3

### PR DESCRIPTION
**Pull request by ChrisB9**
This already enables the v11 support.
We should consider:
- add a new version branch that only supports v10 and v11
- make it php 7.4, php 8.0 and php 8.1 only
- refactor and remove legacy code
- add github workflow for phpstan & phpcs

> Note: I think we should furthermore consider during all that refactoring #6

### CODE REVIEW

**Comment by NarkNiro** [comment]
According to Composer we still support TYPO3 v8 and v9 in these there is no dependency injection yet =/

**Comment by ChrisB9** [comment]
which is why I would like to drop support for it

**Comment by andreaswolf** [comment]
I merged #8 now, but I think we should add some parts of this as well – at least the CI parts, the class finalization and the restriction to PHP 7.4+ would be beneficial IMO.

**Comment by ChrisB9** [comment]
Should we then continue with this MR or break those ideas into multiple requests and drop the namespace change?

**Comment by ChrisB9** [comment]
I am going to close this as we added github actions through #14 and #15 
I'll add an issue for the namespace topic

**Pull request closed without merging**
